"""update product

Revision ID: 3107ca8d0c2a
Revises: f4970d323e66
Create Date: 2021-10-01 09:53:42.715296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3107ca8d0c2a'
down_revision = 'f4970d323e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.Float(), nullable=True))
    op.drop_column('product', 'created_at')
    op.drop_column('product', 'updated_at')
    op.drop_column('transaction', 'created_at')
    op.drop_column('transaction', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('transaction', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('product', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('product', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
