"""empty message

Revision ID: 713d0875906b
Revises: da9cd35b4e11
Create Date: 2021-09-29 15:46:32.019160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '713d0875906b'
down_revision = 'da9cd35b4e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('stocks', sa.BigInteger(), nullable=True))
    op.add_column('transaction', sa.Column('quantity', sa.BigInteger(), nullable=False))
    op.alter_column('transaction', 'product_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'product_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    op.drop_column('transaction', 'quantity')
    op.drop_column('product', 'stocks')
    # ### end Alembic commands ###
